export const candidates = [
  {
    id: 1,
    name: "Aaliyah Sanderson",
    location: "Riyadh, Saudi Arabia",
    education: "Bachelor - Cambridge University (2023 - 2023)",
    hashtags: ["top_candidate", "top_candidate"],
    city: "New York",
    viewsCount: 0,
    programCount: 0,
  },
  {
    id: 2,
    name: "Aaliyah Sanderson",
    location: "Riyadh, Saudi Arabia",
    education: "Bachelor - Cambridge University (2023 - 2023)",
    hashtags: ["top_candidate", "top_candidate"],
    city: "New York",
    viewsCount: 0,
    programCount: 0,
  },
  {
    id: 3,
    name: "Aaliyah Sanderson",
    location: "Riyadh, Saudi Arabia",
    education: "Bachelor - Cambridge University (2023 - 2023)",
    hashtags: ["top_candidate", "top_candidate"],
    city: "New York",
    viewsCount: 0,
    programCount: 0,
  },
  {
    id: 4,
    name: "Aaliyah Sanderson",
    location: "Riyadh, Saudi Arabia",
    education: "Bachelor - Cambridge University (2023 - 2023)",
    hashtags: ["top_candidate", "top_candidate"],
    city: "New York",
    viewsCount: 0,
    programCount: 0,
  },  {
    id: 5,
    name: "Aaliyah Sanderson",
    location: "Riyadh, Saudi Arabia",
    education: "Bachelor - Cambridge University (2023 - 2023)",
    hashtags: ["top_candidate", "top_candidate"],
    city: "New York",
    viewsCount: 0,
    programCount: 0,
  },  {
    id: 6,
    name: "Aaliyah Sanderson",
    location: "Riyadh, Saudi Arabia",
    education: "Bachelor - Cambridge University (2023 - 2023)",
    hashtags: ["top_candidate", "top_candidate"],
    city: "New York",
    viewsCount: 5,
    programCount: 5,
  },
];
